CREATE OR REPLACE PROCEDURE SP_LISTA_SOLICITUD_DETALLE(
P_COD_LINEA_NEGOCIO IN CHAR,
P_COD_MODAL_EST IN CHAR,
P_COD_PERIODO IN CHAR,
P_COD_TRAMITE IN NUMBER,
P_ESTADO IN VARCHAR2,
RS_RESULTADO OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN RS_RESULTADO FOR
  SELECT T1.COD_LINEA_NEGOCIO,
         T1.COD_MODAL_EST,
         T1.COD_PERIODO,
         T1.COD_PERIODO,
         T1.COD_TRAMITE,
         T1.COD_UNICO,
         T1.ESTADO,
         T1.COD_ALUMNO,
         T2.COD_DETALLE,
         T2.COD_CURSO,
         T2.COD_TIPO_PRUEBA,
         T2.NUM_PRUEBA,
         T2.SECCION,
         T2.GRUPO,
         T2.ESTADO_CURSO
  FROM SOLICITUD T1 JOIN DETALLE_SOLICITUD T2 ON T1.COD_UNICO = T2.COD_UNICO
  WHERE (P_COD_LINEA_NEGOCIO IS NULL OR  T1.COD_LINEA_NEGOCIO = P_COD_LINEA_NEGOCIO) AND
       (P_COD_MODAL_EST IS NULL OR  T1.COD_MODAL_EST = P_COD_MODAL_EST) AND
       (P_COD_PERIODO IS NULL OR  T1.COD_PERIODO = P_COD_PERIODO) AND
       (P_COD_TRAMITE = 0  OR  T1.COD_TRAMITE = P_COD_TRAMITE) AND
       (P_ESTADO IS NULL OR  T1.ESTADO = P_ESTADO);
END;
